version: 2.1

executors:
  aebuilder:
    docker:
      - image: aeternity/builder
        user: builder
    working_directory: ~/aesophia

jobs:
  build:
    executor: aebuilder
    steps:
      - checkout
      - run:
          name: Build
          command: ./rebar3 escriptize
      - run:
          name: Test
          command: ./test/test_cli.sh
      - run:
          name: Prepare build artifacts
          command: |
            mkdir /tmp/artifacts
            mv aesophia_cli /tmp/artifacts/aesophia_cli-${CIRCLE_SHA1:?}
            chmod +x /tmp/artifacts/aesophia_cli-${CIRCLE_SHA1:?}
      - store_artifacts:
          path: /tmp/artifacts
          destination: /
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - "*"
